insert into professor (id, nome) values (null, 'Gilmar Arantes');
insert into professor (id, nome) values (null, 'Rubens de Castro Pereira');
insert into professor (id, nome) values (null, 'Walison Cavalcanti Moreira');
insert into professor (id, nome) values (null, 'Fábio Nogueira de Lucena');
insert into aluno (id, nome, matricula) values (null, 'Pedro Basilio de Camargo Neto', 201602511);
insert into aluno (id, nome, matricula) values (null, 'Fernando Henrique Quicano Callata', 201609821);
insert into aluno (id, nome, matricula) values (null, 'Saulo de Araújo Calixto', 201609824);
insert into aluno (id, nome, matricula) values (null, 'Lucas Sampaio Dias', 201602502);
insert into aluno (id, nome, matricula) values (null, 'Gustavo Henrique da Silva Batista', 201602493);
insert into aluno (id, nome, matricula) values (null, 'Gabriel Pacheco Peres Pereira de Menezes', 201602492);
insert into aluno (id, nome, matricula) values (null, 'Marcos Rafael Lapa de Sousa', 201607112);
insert into aluno (id, nome, matricula) values (null, 'Murillo Silva e Nunes', 201611905);
insert into aluno (id, nome, matricula) values (null, 'Erik Raphael Ribeiro da Costa', 201203663);
insert into turma (id, disciplina, ano, semestre) values (null, 'Desenvolvimento de Software para Web', 2019, 1);
insert into turma (id, disciplina, ano, semestre) values (null, 'Desenvolvimento de Software para Persistência', 2019, 1);
insert into turma (id, disciplina, ano, semestre) values (null, 'Integração de Aplicações', 2019, 1);
insert into turma (id, disciplina, ano, semestre) values (null, 'Projeto de Software', 2019, 1);