insert into professor (nome) values ("Gilmar Arantes");
insert into professor (nome) values ("Rubens de Castro Pereira");
insert into professor (nome) values ("Walison Cavalcanti Moreira");
insert into professor (nome) values ("Fábio Nogueira de Lucena");
insert into aluno (nome, matricula) values ("Pedro Basilio de Camargo Neto", 201602511);
insert into aluno (nome, matricula) values ("Fernando Henrique Quicano Callata", 201609821);
insert into aluno (nome, matricula) values ("Saulo de Araújo Calixto", 201609824);
insert into aluno (nome, matricula) values ("Lucas Sampaio Dias", 201602502);
insert into aluno (nome, matricula) values ("Gustavo Henrique da Silva Batista", 201602493);
insert into aluno (nome, matricula) values ("Gabriel Pacheco Peres Pereira de Menezes", 201602492);
insert into aluno (nome, matricula) values ("Marcos Rafael Lapa de Sousa", 201607112);
insert into aluno (nome, matricula) values ("Murillo Silva e Nunes", 201611905);
insert into aluno (nome, matricula) values ("Erik Raphael Ribeiro da Costa", 201203663);
insert into turma (disciplina, ano, semestre) values ("Desenvolvimento de Software para Web", 2019, 1);
insert into turma (disciplina, ano, semestre) values ("Desenvolvimento de Software para Persistência", 2019, 1);
insert into turma (disciplina, ano, semestre) values ("Integração de Aplicações", 2019, 1);
insert into turma (disciplina, ano, semestre) values ("Projeto de Software", 2019, 1);